services:
  pg-tests-runner:
    build:
      context: .
      dockerfile: Dockerfile.tests
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        UNAME: node
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
      - ./src/tests/playwright/:/app/src/tests/playwright:rw
    command: "pnpm exec playwright test"
