services:
  pg-tests-runner:
    build:
      context: .
      dockerfile: Dockerfile.tests
    user: root
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
      - ./src/tests/playwright/:/app/src/tests/playwright:rw
    command: "pnpm exec playwright test"
