# Prebuilt MS image
FROM mcr.microsoft.com/playwright:focal

ARG UID
ARG GID
ARG UNAME=node

RUN groupadd --gid $GID --non-unique node
RUN useradd --create-home --uid $UID --gid $GID --non-unique --shell /bin/bash node

RUN mkdir -p /app
RUN chown $UNAME:$UNAME /app

USER $UNAME
WORKDIR /app

COPY --chown=$UNAME:$UNAME . .
COPY --chown=$UNAME:$UNAME .env.tests .env

RUN yarn install --immutable

USER root
RUN yarn playwright install --with-deps chromium

USER $UNAME
RUN yarn build

# Expose port
EXPOSE 4040

CMD ["yarn", "playwright", "test"]
