# Prebuilt MS image
FROM mcr.microsoft.com/playwright:focal

RUN mkdir -p /app
WORKDIR /app

COPY . .
COPY .env.dist .env.production

RUN yarn install
RUN yarn build

# Expose port
EXPOSE 4040

CMD ["yarn", "playwright", "test"]