import { execSync } from 'child_process';
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const newVersion = process.argv[2];
if (!newVersion) {
    console.error('Usage: tsx scripts/release.ts <new-version>');
    process.exit(1);
}

const pkgPath = resolve(__dirname, '../package.json');

async function bumpVersion(branch: string): Promise<void> {
    execSync(`git checkout ${branch}`, { stdio: 'inherit' });
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
    if (pkg.version === newVersion) {
        console.log(`package.json already at version ${newVersion} on ${branch}, skipping commit.`);
        return;
    }
    pkg.version = newVersion;
    writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
    execSync('git add package.json', { stdio: 'inherit' });
    execSync(`git commit -m "chore(${branch}): bump version to ${newVersion}"`, { stdio: 'inherit' });
    execSync(`git push origin ${branch}`, { stdio: 'inherit' });
    console.log(`Updated package.json and pushed to ${branch}`);
}

async function main(): Promise<void> {
    await bumpVersion('development');

    try {
        execSync('git checkout master', { stdio: 'inherit' });
        execSync('git merge development', { stdio: 'inherit' });
        console.log('Merged development into master');
    } catch (err) {
        console.error('Error merging development into master:', err);
        console.error('Abort release process. Resolve merge conflicts and try again.');
        process.exit(1);
    }

    await bumpVersion('master');

    execSync(`git tag v${newVersion}`, { stdio: 'inherit' });
    execSync('git push origin master', { stdio: 'inherit' });
    execSync('git push origin --tags', { stdio: 'inherit' });
    console.log(`Created and pushed tag v${newVersion}`);

    try {
        execSync(`gh release create v${newVersion} --title "Release v${newVersion}" --generate-notes`, {
            stdio: 'inherit',
        });
        console.log('GitHub release created with autogenerated notes');
    } catch (err) {
        console.warn('GitHub CLI not found or release failed. Please create the release manually.');
        console.warn('Error details:', err);
    }
}

main();
