name: CI
on: push
permissions:
  contents: read
jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          version: "10.33.0"

      - name: Set Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24.x"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: TypeScript Typecheck
        run: pnpm run typecheck

      - name: Lint Code
        run: pnpm run lint

      - name: Check Code Formatting
        run: pnpm run format

      - name: Build Production Project
        run: |
          cp .env.test .env.production
          pnpm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: dist
          path: dist

      - name: Run Unit Tests
        run: pnpm run test

  e2e:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: node:24-slim@sha256:b506e7321f176aae77317f99d67a24b272c1f09f1d10f1761f2773447d8da26c
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install pnpm
        run: npm i -g pnpm@10.33.0

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_DIR=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_DIR }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Download dist artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: dist
          path: dist

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Install Playwright
        run: pnpm add -D @playwright/test && pnpm exec playwright install --with-deps chromium

      - name: Run E2E Tests
        run: pnpm exec playwright test --reporter=line

      - name: Upload results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: always()
        with:
          name: pw-results
          path: src/tests/playwright/results

      - name: Upload reports
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: pw-report
          path: src/tests/playwright/report
