name: Deploy to SFTP
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install pnpm
        uses: pnpm/action-setup@71c92474e7e4f5bca283fb17ef80fba9cdb2b4b1 # v6
        with:
          version: "10.33.0"
      - name: Set Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "24.x"
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Create .env.production file
        run: |
          echo "VITE_TRACK_GA_MEASUREMENT_ID='${{ vars.VITE_TRACK_GA_MEASUREMENT_ID }}'" >> .env.production
          echo "VITE_API_URL='${{ vars.VITE_API_URL }}'" >> .env.production
          echo "VITE_RECAPTCHA_SITE_KEY='${{ vars.VITE_RECAPTCHA_SITE_KEY }}'" >> .env.production
          echo "VITE_RECAPTCHA_SECRET_KEY='${{ vars.VITE_RECAPTCHA_SECRET_KEY }}'" >> .env.production
      - name: Build Project
        run: pnpm run build
      - name: Deploy to SFTP
        uses: wlixcc/SFTP-Deploy-Action@a5ccb9c6211a94cc59404f0fdb2a9936a6dfee64 # v1.2.6
        with:
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT || 22 }}
          local_path: "./dist/*"
          remote_path: ${{ secrets.FTP_REMOTE_PATH }}
