name: Deploy to SFTP
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4
        with:
          version: "10.32.1"
      - name: Set Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24.x"
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Create .env.production file
        run: |
          echo "VITE_TRACK_GA_ID='${{ vars.VITE_TRACK_GA_ID }}'" > .env.production
          echo "VITE_TRACK_GA_MEASUREMENT_ID='${{ vars.VITE_TRACK_GA_MEASUREMENT_ID }}'" >> .env.production
          echo "VITE_SERVER_URL='${{ vars.VITE_SERVER_URL }}'" >> .env.production
          echo "VITE_RECAPTCHA_SITE_KEY='${{ vars.VITE_RECAPTCHA_SITE_KEY }}'" >> .env.production
          echo "VITE_RECAPTCHA_SECRET_KEY='${{ vars.VITE_RECAPTCHA_SECRET_KEY }}'" >> .env.production
      - name: Build Project
        run: pnpm run build
      - name: Deploy to SFTP
        uses: wlixcc/SFTP-Deploy-Action@a5ccb9c6211a94cc59404f0fdb2a9936a6dfee64 # v1.2.6
        with:
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT || 22 }}
          local_path: "./dist/*"
          remote_path: ${{ secrets.FTP_REMOTE_PATH }}
