name: Deploy to SFTP
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
        with:
          version: "11.25.0"
      - name: Set Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: "24.x"
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Create .env.production file
        run: |
          echo "VITE_TRACK_GA_MEASUREMENT_ID='${{ vars.VITE_TRACK_GA_MEASUREMENT_ID }}'" >> .env.production
          echo "VITE_API_URL='${{ vars.VITE_API_URL }}'" >> .env.production
          echo "VITE_RECAPTCHA_SITE_KEY='${{ vars.VITE_RECAPTCHA_SITE_KEY }}'" >> .env.production
          echo "VITE_RECAPTCHA_SECRET_KEY='${{ vars.VITE_RECAPTCHA_SECRET_KEY }}'" >> .env.production
      - name: Build Project
        run: pnpm run build
      - name: Deploy to SFTP
        uses: wlixcc/SFTP-Deploy-Action@a5ccb9c6211a94cc59404f0fdb2a9936a6dfee64 # v1.2.6
        with:
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT || 22 }}
          local_path: "./dist/*"
          remote_path: ${{ secrets.FTP_REMOTE_PATH }}
