name: CI
on: push
jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Check Build
        run: |
          cp .env.dist .env.production
          yarn build
      - name: Run Code Analysis
        run: |
          yarn prettify
          yarn lint
      - name: Run Tests - Jest
        run: yarn tests:jest
      - name: Runu Tests - Playwright
        run: |
          yarn tests:pw:build
          yarn tests:pw:run
