name: CI
on: push
jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Dump UID & GID
        run: |
          echo User ID [UID]: $(id -u)
          echo Group ID [GID]: $(id -g)
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Check Build
        run: |
          cp .env.dist .env.production
          yarn build
      - name: Code Analysis
        run: |
          yarn prettify
          yarn lint
      - name: Jest Tests
        run: yarn tests:jest
      - name: Playwright Tests
        run: |
          yarn tests:pw:build
          yarn tests:pw:run
